### ISSUE TITLE
Sequence diagrams don't get generated correctly using mermaid

### ISSUE THREAD

**Issue by joshcarp** [joshcarp/syslcatalog#202]
Given a project, when a sequence diagram is generated using plantuml it shows as this:

![image](https://user-images.githubusercontent.com/32605850/90460630-9cee1e00-e147-11ea-9ad1-f2234000b171.png)

But the mermaid sequence diagram is shown as this: 
![image](https://user-images.githubusercontent.com/32605850/90460715-d7f05180-e147-11ea-835f-34ce3a5308cf.png)

There is a missing mastercard call

This stems from plantuml using the `RootModule` field on the generator object, whereas the mermaid library only uses the current contextual module `Module` which only has apps with the same `@project` attribute. 

This would be the canonical sysl that wouldn't work:
```
foo:
    @package = "foo"
    ep:
        bah <- ep
bah:
   @package="bah"
   ep:
        return 
```

Expected diagram:
![image](https://user-images.githubusercontent.com/32605850/90461203-04589d80-e149-11ea-8e73-283736076376.png)
Actual Diagram:

I actually had trouble even generating this diagram, but you get the point

**Comment by ChloePlanet** [comment]
solved: https://demo.sysl.io/backend/paymentserver/
